<script lang="ts">
</script>

<h1 class="marck-script text-center text-8xl">Sources</h1>

<div class="flex min-h-screen flex-col">
	<div class="mx-4 lg:mx-auto lg:w-1/3">
		<p>
			The main data used in the calculator has been taken from <a
				href="https://ourworldindata.org/agricultural-land-by-global-diets"
				class="underline"
				target="_blank">Our World in Data</a
			>.
		</p>
		<p class="rounded border-2 border-gray-600 bg-gray-200 p-1 font-mono">
			Hannah Ritchie (2017) - “How much of the world’s land would we need in order to feed the
			global population with the average diet of a given country?” Published online at
			OurWorldinData.org. Retrieved from:
			'https://ourworldindata.org/agricultural-land-by-global-diets' [Online Resource]
		</p>
		<p>
			Additional data (Weight per unit and color) have been generated by a mixture of ChatGPT and
			Llama3.1.
		</p>
		<p>
			Furthermore, the information about the HALF index and its whole concept have been inferred
			from <a
				href="https://doi.org/10.1016/j.gloenvcha.2016.09.005"
				target="_blank"
				class="underline">Human appropriation of land for food: The role of diet</a
			>
			(https://doi.org/10.1016/j.gloenvcha.2016.09.005). Data from
			<a
				href="https://ourworldindata.org/grapher/share-of-global-habitable-land-needed-for-agriculture-if-everyone-had-the-diet-of?tab=table"
				target="_blank">OurWorldInData</a
			> has also been incorporated as the sources fpor the different HALF indexes per country
		</p>
	</div>
</div>
